---

- name: configure_kvm | Load all groups
  getent:
    database: group
    split: ':'
  check_mode: false

- name: configure_kvm | Set unix_sock_group
  set_fact:
    kvm_unix_sock_group: "{{ ('libvirtd' in getent_group) | ternary('libvirtd', 'libvirt') }}"
  when:
    - getent_group is defined
    - "'libvirt' in getent_group or 'libvirtd' in getent_group"

- name: configure_kvm | Drop libvirtd.conf
  template:
    src: libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: restart libvirtd
  when: not ansible_check_mode