---
kvm_hosts:
  hosts:
    host1:
      ansible_user: root
      ansible_host: 10.11.10.105
      hostname: titanic.qcu87z.net
vms:
  hosts:
    minecraft:
      ansible_user: ansible
      ansible_host: 10.11.10.106
      ansible_pass: "{{ vault_ansible_pass }}"
      hostname: minecraft.kvm.qcu87z.net
    unms:
      ansible_user: ansible
      ansible_host: 10.11.10.107
      ansible_pass: "{{ vault_ansible_pass }}"
      hostname: unms.kvm.qcu87z.net
    grafana:
      ansible_user: ansible
      ansible_host: 10.11.10.109
      hostname: grafana.kvm.qcu87z.net
    influxdb:
      ansible_user: ansible
      ansible_host: 10.11.10.110
      hostname: influxdb.kvm.qcu87z.net
    prometheus:
      ansible_user: ansible
      ansible_host: 10.11.10.111
      hostname: prometheus.kvm.qcu87z.net
  vars:
    common_packages:
      - htop
      - vim
      - ack
      - net-tools
      - bind-utils
      - qemu-guest-agent