---
kvm_hosts:
  hosts:
    host1:
      ansible_user: ashley
      ansible_host: 10.11.12.209
vms:
  hosts:
    vmX2:
      ansible_user: ansible
      ansible_host: 10.11.12.205
      ansible_pass: "Gils77@apartStea1Gn0me!1"